name: Сборка

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Сборка"
    steps:
      - name: Получаем исходники
        uses: actions/checkout@v3

      - name: Устанавливаем Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Устанавлиаем зависимости
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -U -r requirements.txt
          pip install -U sphinxawesome-theme --pre
      
      - name: Собираем гайд
        shell: bash
        run: |
          sphinx-build -M html source build

      - name: Загружаем артефакт
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build/html"

  deploy:
    runs-on: ubuntu-latest
    name: "Загрузка на GitHub Pages"
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Получаем исходники
        uses: actions/checkout@v3

      - name: Настраиваем GitHub Pages
        uses: actions/configure-pages@v3

      - name: Загружаем
        id: deployment
        uses: actions/deploy-pages@v2